// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Bus struct {
	ID          string  `json:"id"`
	Driver      *Driver `json:"-"`
	PlateNumber string  `json:"plate_number"`
	Model       string  `json:"model"`
	DriverId    string  `json:"driver"`
}

type Driver struct {
	ID string `json:"id"`
	// TODO: extend driver from user
	User          *User  `json:"-"`
	Bus           *Bus   `json:"-"`
	LicenseNumber string `json:"license_number"`
	BusId         string `json:"bus"`
	UserId        string `json:"user"`
}

// TODO: localizization
//
//	fuck localization
type Notification struct {
	ID             string                       `json:"id"`
	Title          string                       `json:"title"`
	Body           string                       `json:"body"`
	SentAt         string                       `json:"sent_at"`
	Sender         *User                        `json:"-"`
	SenderID       string                       `json:"sender_id"`
	TargetAudience []NotificationTargetAudience `json:"target_audience"`
	DeliveryMethod []NotificationDeliveryMethod `json:"delivery_method"`
	SentBy         string                       `json:"sent_by"`
}

type SendNotificationInput struct {
	Title          string                       `json:"title"`
	Body           string                       `json:"body"`
	TargetAudience []NotificationTargetAudience `json:"target_audience"`
	DeliveryMethod []NotificationDeliveryMethod `json:"delivery_method"`
}

type User struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Email  string  `json:"email"`
	Avatar *string `json:"avatar,omitempty"`
}

type NotificationDeliveryMethod string

const (
	NotificationDeliveryMethodEmail      NotificationDeliveryMethod = "email"
	NotificationDeliveryMethodMobilePush NotificationDeliveryMethod = "mobile_push"
)

var AllNotificationDeliveryMethod = []NotificationDeliveryMethod{
	NotificationDeliveryMethodEmail,
	NotificationDeliveryMethodMobilePush,
}

func (e NotificationDeliveryMethod) IsValid() bool {
	switch e {
	case NotificationDeliveryMethodEmail, NotificationDeliveryMethodMobilePush:
		return true
	}
	return false
}

func (e NotificationDeliveryMethod) String() string {
	return string(e)
}

func (e *NotificationDeliveryMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationDeliveryMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationDeliveryMethod", str)
	}
	return nil
}

func (e NotificationDeliveryMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NotificationTargetAudience string

const (
	NotificationTargetAudiencePassengers NotificationTargetAudience = "passengers"
	NotificationTargetAudienceDrivers    NotificationTargetAudience = "drivers"
)

var AllNotificationTargetAudience = []NotificationTargetAudience{
	NotificationTargetAudiencePassengers,
	NotificationTargetAudienceDrivers,
}

func (e NotificationTargetAudience) IsValid() bool {
	switch e {
	case NotificationTargetAudiencePassengers, NotificationTargetAudienceDrivers:
		return true
	}
	return false
}

func (e NotificationTargetAudience) String() string {
	return string(e)
}

func (e *NotificationTargetAudience) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationTargetAudience(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationTargetAudience", str)
	}
	return nil
}

func (e NotificationTargetAudience) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
